/**
 * AWS Signature Version 4, enough of it for S3-compatible object storage.
 *
 * Hand-rolled on `node:crypto` rather than pulling in `@aws-sdk/client-s3` and
 * its ~40 transitive packages — the same instinct that put `node:sqlite` in
 * `db.ts` instead of a native SQLite driver. We need four operations (presign
 * GET, presign PUT, HEAD, DELETE), and this is the whole of what they require.
 *
 * Correctness is not taken on trust: `sigv4.test.ts` checks every signature
 * against reference values generated by botocore, AWS's own implementation.
 *
 * Server-only — it handles the secret access key and must never be imported
 * from a client component.
 */

import { createHash, createHmac } from "node:crypto";

const ALGORITHM = "AWS4-HMAC-SHA256";

/**
 * S3 presigned URLs sign no body: the client sends bytes we never see, so
 * there is nothing to hash at signing time.
 */
const UNSIGNED_PAYLOAD = "UNSIGNED-PAYLOAD";

export interface SigV4Credentials {
  accessKeyId: string;
  secretAccessKey: string;
  /** Only set when signing with temporary STS credentials. */
  sessionToken?: string;
}

interface SigningContext {
  region: string;
  service: string;
  credentials: SigV4Credentials;
  /** Defaults to now; tests pin it so signatures are reproducible. */
  date?: Date;
}

/**
 * Percent-encode per RFC 3986, which is stricter than `encodeURIComponent`:
 * that leaves `!'()*` untouched, and a canonical request built with it
 * produces a signature S3 rejects with an opaque SignatureDoesNotMatch.
 */
export function uriEncode(
  value: string,
  { encodeSlash = true }: { encodeSlash?: boolean } = {},
): string {
  let out = "";
  for (const byte of Buffer.from(value, "utf8")) {
    const char = String.fromCharCode(byte);
    if (
      (byte >= 0x41 && byte <= 0x5a) || // A-Z
      (byte >= 0x61 && byte <= 0x7a) || // a-z
      (byte >= 0x30 && byte <= 0x39) || // 0-9
      char === "-" ||
      char === "_" ||
      char === "." ||
      char === "~"
    ) {
      out += char;
    } else if (char === "/" && !encodeSlash) {
      out += char;
    } else {
      out += `%${byte.toString(16).toUpperCase().padStart(2, "0")}`;
    }
  }
  return out;
}

function sha256Hex(payload: string): string {
  return createHash("sha256").update(payload, "utf8").digest("hex");
}

function hmac(key: Buffer | string, data: string): Buffer {
  return createHmac("sha256", key).update(data, "utf8").digest();
}

/** `20260814T101112Z` and its `20260814` date stamp. */
function formatDate(date: Date): { amzDate: string; dateStamp: string } {
  const amzDate = date.toISOString().replace(/[-:]/g, "").replace(/\.\d+/, "");
  return { amzDate, dateStamp: amzDate.slice(0, 8) };
}

function credentialScope(dateStamp: string, region: string, service: string) {
  return `${dateStamp}/${region}/${service}/aws4_request`;
}

function signingKey(
  secretAccessKey: string,
  dateStamp: string,
  region: string,
  service: string,
): Buffer {
  const dateKey = hmac(`AWS4${secretAccessKey}`, dateStamp);
  const regionKey = hmac(dateKey, region);
  const serviceKey = hmac(regionKey, service);
  return hmac(serviceKey, "aws4_request");
}

/**
 * Sorted by encoded key, then encoded value — byte order, which is why this
 * sorts the already-encoded pairs rather than the raw ones.
 */
function canonicalQueryString(params: Record<string, string>): string {
  return Object.entries(params)
    .map(([key, value]) => [uriEncode(key), uriEncode(value)] as const)
    .sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : a[1] < b[1] ? -1 : 1))
    .map(([key, value]) => `${key}=${value}`)
    .join("&");
}

function buildCanonicalRequest({
  method,
  canonicalUri,
  query,
  headers,
  payloadHash,
}: {
  method: string;
  canonicalUri: string;
  query: Record<string, string>;
  headers: Record<string, string>;
  payloadHash: string;
}): { canonicalRequest: string; signedHeaders: string } {
  const normalized = Object.entries(headers)
    .map(([name, value]) => [name.toLowerCase(), value.trim()] as const)
    .sort((a, b) => (a[0] < b[0] ? -1 : 1));

  const canonicalHeaders = normalized
    .map(([name, value]) => `${name}:${value}\n`)
    .join("");
  const signedHeaders = normalized.map(([name]) => name).join(";");

  return {
    canonicalRequest: [
      method,
      canonicalUri,
      canonicalQueryString(query),
      canonicalHeaders,
      signedHeaders,
      payloadHash,
    ].join("\n"),
    signedHeaders,
  };
}

function computeSignature({
  canonicalRequest,
  amzDate,
  dateStamp,
  region,
  service,
  secretAccessKey,
}: {
  canonicalRequest: string;
  amzDate: string;
  dateStamp: string;
  region: string;
  service: string;
  secretAccessKey: string;
}): string {
  const stringToSign = [
    ALGORITHM,
    amzDate,
    credentialScope(dateStamp, region, service),
    sha256Hex(canonicalRequest),
  ].join("\n");

  return hmac(
    signingKey(secretAccessKey, dateStamp, region, service),
    stringToSign,
  ).toString("hex");
}

/**
 * A URL carrying its own credentials in the query string, valid for
 * `expiresIn` seconds. The browser then talks to the bucket directly and the
 * app never touches the bytes.
 *
 * `url` must already be percent-encoded — build the key with
 * `uriEncode(key, { encodeSlash: false })`.
 */
export function presignUrl({
  method,
  url,
  expiresIn,
  query = {},
  region,
  service,
  credentials,
  date = new Date(),
}: SigningContext & {
  method: string;
  url: string;
  expiresIn: number;
  query?: Record<string, string>;
}): string {
  const target = new URL(url);
  const { amzDate, dateStamp } = formatDate(date);

  const signedQuery: Record<string, string> = {
    ...Object.fromEntries(target.searchParams.entries()),
    ...query,
    "X-Amz-Algorithm": ALGORITHM,
    "X-Amz-Credential": `${credentials.accessKeyId}/${credentialScope(dateStamp, region, service)}`,
    "X-Amz-Date": amzDate,
    "X-Amz-Expires": String(expiresIn),
    "X-Amz-SignedHeaders": "host",
  };
  if (credentials.sessionToken) {
    signedQuery["X-Amz-Security-Token"] = credentials.sessionToken;
  }

  const { canonicalRequest } = buildCanonicalRequest({
    method,
    canonicalUri: target.pathname,
    query: signedQuery,
    headers: { host: target.host },
    payloadHash: UNSIGNED_PAYLOAD,
  });

  const signature = computeSignature({
    canonicalRequest,
    amzDate,
    dateStamp,
    region,
    service,
    secretAccessKey: credentials.secretAccessKey,
  });

  return `${target.origin}${target.pathname}?${canonicalQueryString({
    ...signedQuery,
    "X-Amz-Signature": signature,
  })}`;
}

/**
 * Authorization headers for a request the server makes itself (HEAD to read an
 * object's size, DELETE to remove it).
 *
 * Unlike a presigned URL, here we hold the body and so hash it for real — an
 * empty string for every call this module makes. That is what botocore's S3
 * signer does, and it is what the vectors in `sigv4.test.ts` pin.
 */
export function signRequestHeaders({
  method,
  url,
  headers = {},
  payload = "",
  region,
  service,
  credentials,
  date = new Date(),
}: SigningContext & {
  method: string;
  url: string;
  headers?: Record<string, string>;
  payload?: string;
}): Record<string, string> {
  const target = new URL(url);
  const { amzDate, dateStamp } = formatDate(date);
  const payloadHash = sha256Hex(payload);

  const allHeaders: Record<string, string> = {
    ...headers,
    host: target.host,
    "x-amz-content-sha256": payloadHash,
    "x-amz-date": amzDate,
  };
  if (credentials.sessionToken) {
    allHeaders["x-amz-security-token"] = credentials.sessionToken;
  }

  const { canonicalRequest, signedHeaders } = buildCanonicalRequest({
    method,
    canonicalUri: target.pathname,
    query: Object.fromEntries(target.searchParams.entries()),
    headers: allHeaders,
    payloadHash,
  });

  const signature = computeSignature({
    canonicalRequest,
    amzDate,
    dateStamp,
    region,
    service,
    secretAccessKey: credentials.secretAccessKey,
  });

  return {
    ...allHeaders,
    Authorization:
      `${ALGORITHM} Credential=${credentials.accessKeyId}/${credentialScope(dateStamp, region, service)}, ` +
      `SignedHeaders=${signedHeaders}, Signature=${signature}`,
  };
}
